app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['namespace' => 'Admin'], function(){
	Route::get('login', 'AdminController@login');
	Route::get('logout', 'AdminController@logout');
	Route::post('login', 'AdminController@postlogin');
	Route::post('upload', 'AdminController@upload');
});


// Admin Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function(){
	// Resources
	Route::resource('artist', 'ArtistController');
	Route::resource('track', 'TrackController');
	Route::resource('video', 'VideoController');
	Route::resource('playlist', 'PlaylistController');
	Route::resource('user', 'UserController');

	Route::group(['prefix' => 'bulk'], function(){
		Route::get('track/add', function(){
			return ['page' => 'add bulk tracks'];
		});
		Route::get('video/add', function(){
			return ['page' => 'add bulk videos'];			
		});
	});

	Route::get('/', 'AdminController@home');
	Route::get('settings', 'AdminController@settings');
});


// Route for api
Route::group(['prefix' => 'api', 'namespace' => 'Api'], function(){
	Route::any('/', function(){
		return [
			"api_version" => env('API_VERSION'),
			"app_version" => env('APP_VERSION'),
		];
	});
	Route::resource('artist', 'ArtistController');
	Route::resource('track', 'TrackController');
	Route::resource('video', 'VideoController');
	Route::resource('playlist', 'PlaylistController');
	Route::resource('user', 'UserController');
});

app/Models/Track.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

class Track extends Model
{
    protected $fillable = [
    	'title',
    	'artist',
    	'file'
    ];

    public function getStatusAttribute($value){
        if($value == '1'){
            return true;
        }
        else{
            return false;
        }
    }

    public function getCreatedByAttribute($value){
        return (int)$value;
    }

    public function getCreatedAtAttribute($value){
        $time = strtotime($value);

        return Carbon::createFromTimestamp($time)->diffForHumans();
    }

    public function getUpdatedAtAttribute($value){
        $time = strtotime($value);

        return Carbon::createFromTimestamp($time)->diffForHumans();
    }


    public function artists(){
    	return $this->hasOne('App\Models\Artist', 'id', 'artist');
    } 

    public function audio(){
        return $this->hasOne('App\Models\File', 'id', 'file');
    }
}

resources/views/admin/artist.blade.php
@extends('admin.master')

@section('title')
All Artists | Admin
@endsection
@section('container')
	<div class="row">
		@foreach($artists as $artist)
			<div class="col-md-3 col-sm-12">
				<div class="thumbnail">
					<img src="{{ url($artist->image->url) }}" alt="{{ $artist->name }}">
					<div class="caption">
						<h3><a href="{{ url('admin/artist/'.$artist->id.'/edit') }}">{{ $artist->name}}</a></h3>
						{!! Form::open(["method" => "delete", "route" => ["admin.artist.destroy", $artist->id]]) !!}
							<a href="{{ url('admin/artist/'.$artist->id.'/edit') }}" class="btn btn-info">Edit Artist</a>
							<button type="submit" class="btn btn-danger">Delete</button>
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		@endforeach
		<div class="col-md-12">
			{{ $artists->links() }}
		</div>
	</div>

@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.master')

@section('container')
	<div class="row">
		<div class="col-md-12">
			<p>Welcome, {{ Auth::user()->name }}</p>
			
		</div>
	</div>
@endsection

resources/views/admin/master.blade.php
@extends('layouts.master')

@section('title', 'Dashboard')

<!-- header -->
@section('header')
    @include('layouts.header')
@endsection

<!-- footer -->
@section('footer')
    @include('layouts.footer')
@endsection

resources/views/admin/track.blade.php
@extends('admin.master')

@section('container')
	<div class="row">
		<div class="col-md-12">
			<h2>All Artists</h2>
			<hr>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Title</th>
						<th>Artist</th>
						<th>Created at</th>
						<th>Updated at</th>
						<th>Edit information</th>
					</tr>
				</thead>
				<tbody>
					@foreach($tracks as $track)
					<tr>
						<td>{{ $track->title }}</td>
						<td>{{ $track->artists->name }}</td>
						<td>{{ $track->created_at }}</td>
						<td>{{ $track->updated_at }}</td>
						<td>
							{!! Form::open(["method" => "delete", "route" => ["admin.track.destroy", $track->id]]) !!}
								<a href="{{url('admin/track/'.$track->id.'/edit')}}" class="btn btn-success btn-xs">Edit</a>
								<button type="submit" class="btn btn-danger btn-xs">Delete</button>
							{!! Form::close() !!}
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
@endsection